### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by alpglide** [ranmeizi/grafana-ProEditTable-panel#1]
I tried, but got this:
![image](https://github.com/ranmeizi/grafana-ProEditTable-panel/assets/8009693/f44802a9-4435-4b51-94b7-c40022b9731a)
how to change language to English?
Thanks in advance.

**Comment by alpglide** [comment]
fixed it:
import enUS from 'antd/locale/en_US';
\<ConfigProvider  locale={enUS}\>

**Comment by alpglide** [comment]
still need more work:  "Add a row of data" clicked more than once. non English characters appears.
![image](https://github.com/ranmeizi/grafana-ProEditTable-panel/assets/8009693/de1ad9b9-eba9-4bc1-9785-b255c3d30829)

**Comment by ranmeizi** [comment]
> still need more work: "Add a row of data" clicked more than once. non English characters appears. ![image](https://private-user-images.githubusercontent.com/8009693/346300548-de1ad9b9-eba9-4bc1-9785-b255c3d30829.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMTEzMzksIm5iZiI6MTcyMDMxMTAzOSwicGF0aCI6Ii84MDA5NjkzLzM0NjMwMDU0OC1kZTFhZDliOS1lYmE5LTRiYzEtOTc4NS1iMjU1YzNkMzA4MjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMDAxMDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzdmZGRjMjM0ZmY4NzUxOTg1MDExYzUyYmM4YmU0OGNlYTk5NjVkOWQ5OTk2YWI1YTIxYWQwZTI4ODM1NGY5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l2UNZnA0G_o8hYqOBa-jWhnDc8RAiZRDLXYnkYBXj4g)

thanks a lot! its useful ,  push in my TODO list

there is lot of english and chinese word in my code. its time to tidy up
